export const USERS_SEED = [
  {
    firstName: 'Super',
    lastName: 'Admin',
    email: 'superadmin@example.com',
    password: 'SuperAdmin@123',
    phoneNumber: '+1234567890',
    isActive: true,
    emailVerified: true,
    role: 'Super Admin',
  },
  {
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@example.com',
    password: 'Admin@123',
    phoneNumber: '+1234567891',
    isActive: true,
    emailVerified: true,
    role: 'Admin',
  },
  {
    firstName: 'Manager',
    lastName: 'User',
    email: 'manager@example.com',
    password: 'Manager@123',
    phoneNumber: '+1234567892',
    isActive: true,
    emailVerified: true,
    role: 'Manager',
  },
  {
    firstName: 'Regular',
    lastName: 'User',
    email: 'user@example.com',
    password: 'User@123',
    phoneNumber: '+1234567893',
    isActive: true,
    emailVerified: true,
    role: 'User',
  },
];
