export const USERS_SEED = [
  {
    firstName: 'Super',
    lastName: 'Admin',
    email: 'superadmin@example.com',
    password: 'SuperAdmin@123',
    phoneNumber: '+1234567890',
    isActive: true,
    emailVerified: true,
    role: 'Super Admin',
  },
  {
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@example.com',
    password: 'Admin@123',
    phoneNumber: '+1234567891',
    isActive: true,
    emailVerified: true,
    role: 'Admin',
  },
  // One login per managed role (all use the password Passw0rd@123).
  {
    firstName: 'Alice',
    lastName: 'Owner',
    email: 'administrator@example.com',
    password: 'Passw0rd@123',
    phoneNumber: '+1234567900',
    isActive: true,
    emailVerified: true,
    role: 'Administrators',
  },
  {
    firstName: 'Dan',
    lastName: 'Rider',
    email: 'delivery@example.com',
    password: 'Passw0rd@123',
    phoneNumber: '+1234567901',
    isActive: true,
    emailVerified: true,
    role: 'Delivery Boys',
  },
  {
    firstName: 'Cara',
    lastName: 'Guest',
    email: 'customer@example.com',
    password: 'Passw0rd@123',
    phoneNumber: '+1234567902',
    isActive: true,
    emailVerified: true,
    role: 'Customers',
  },
  {
    firstName: 'Evan',
    lastName: 'Staff',
    email: 'employee@example.com',
    password: 'Passw0rd@123',
    phoneNumber: '+1234567903',
    isActive: true,
    emailVerified: true,
    role: 'Employees',
  },
  {
    firstName: 'Wendy',
    lastName: 'Server',
    email: 'waiter@example.com',
    password: 'Passw0rd@123',
    phoneNumber: '+1234567904',
    isActive: true,
    emailVerified: true,
    role: 'Waiters',
  },
  {
    firstName: 'Chris',
    lastName: 'Cook',
    email: 'chef@example.com',
    password: 'Passw0rd@123',
    phoneNumber: '+1234567905',
    isActive: true,
    emailVerified: true,
    role: 'Chefs',
  },
];
