"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { QRCodeCanvas } from "qrcode.react";
import { ArrowLeft, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Skeleton } from "@/components/ui/skeleton";
import { useSettingsStore } from "@/hooks/use-settings-store";
import { tableQrUrl } from "@/lib/app-url";
import { groupTablesByFloor } from "@/lib/table-utils";

export default function BranchQrPrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const hydrated = useSettingsStore((s) => s.hydrated);
  const branch = useSettingsStore((s) => s.branches.find((b) => b.id === id));
  const [ready, setReady] = useState(false);

  useEffect(() => {
    if (hydrated) setReady(true);
  }, [hydrated]);

  useEffect(() => {
    document.title = branch ? `${branch.name} — Table QR codes` : "Table QR codes";
  }, [branch]);

  if (!ready) {
    return (
      <div className="p-8">
        <Skeleton className="mb-6 h-8 w-64" />
        <div className="grid grid-cols-3 gap-6">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <Skeleton key={i} className="h-48" />
          ))}
        </div>
      </div>
    );
  }

  if (!branch) {
    return (
      <div className="flex min-h-screen items-center justify-center p-8">
        <EmptyState
          title="Branch not found"
          action={
            <Button asChild variant="outline">
              <Link href="/app/settings">Back to settings</Link>
            </Button>
          }
        />
      </div>
    );
  }

  const grouped = groupTablesByFloor(branch.tables);

  return (
    <div className="min-h-screen bg-white p-6 print:p-0 sm:p-10">
      <div className="mb-8 flex flex-wrap items-center justify-between gap-4 border-b border-border pb-6 print:hidden">
        <Button asChild variant="ghost" size="sm">
          <Link href="/app/settings">
            <ArrowLeft className="size-4" />
            Settings
          </Link>
        </Button>
        <Button onClick={() => window.print()}>
          <Printer className="size-4" />
          Print / Save as PDF
        </Button>
      </div>

      <header className="mb-10 text-center">
        <h1 className="font-display text-2xl font-bold text-ink">{branch.name}</h1>
        <p className="mt-1 text-sm text-muted-foreground">Scan to order · Table QR codes</p>
      </header>

      {branch.tables.length === 0 ? (
        <EmptyState title="No tables configured" description="Add tables in branch settings first." />
      ) : (
        Object.entries(grouped).map(([floor, tables]) => (
          <section key={floor} className="mb-12">
            <h2 className="mb-6 border-b border-border pb-2 font-display text-lg font-semibold text-ink">
              {floor}
            </h2>
            <div className="grid grid-cols-2 gap-8 sm:grid-cols-3 md:grid-cols-4">
              {tables.map((table) => (
                <div
                  key={table.id}
                  className="flex break-inside-avoid flex-col items-center rounded-xl border border-border p-6 text-center"
                >
                  <QRCodeCanvas
                    value={tableQrUrl(table.qrToken)}
                    size={160}
                    level="M"
                    marginSize={2}
                  />
                  <p className="mt-4 font-display text-xl font-bold text-ink">
                    Table {table.label}
                  </p>
                  {table.seats && (
                    <p className="text-sm text-muted-foreground">{table.seats} seats</p>
                  )}
                  <p className="mt-2 max-w-full truncate text-[10px] text-muted-foreground">
                    {tableQrUrl(table.qrToken)}
                  </p>
                </div>
              ))}
            </div>
          </section>
        ))
      )}

      <footer className="mt-12 border-t border-border pt-6 text-center text-xs text-muted-foreground print:hidden">
        Generated by TableTap · {new Date().toLocaleDateString()}
      </footer>
    </div>
  );
}
